### PR TITLE
fix: a header value is not part of an url

### PR DESCRIPTION
**Pull request by lthms**
This is a proposal. I think it works, at least it works for Strings. But I do not have a usecase with something else than a String. Can you try?

### CODE REVIEW

**Comment by eskimor** [comment]
servant does not escape any characters in a header? I am not sure this is valid. What about newlines? I think I have to do my homework and check the http standard about this.

**Comment by eskimor** [comment]
I just used urlencode to be on the safe side, I really have to check whether the http-api-data way is correct - I am a bit skeptic.

**Comment by lthms** [comment]
Why should it escapes character? An header is just a piece of data, IMO. But, I completely understand! If I find anything useful, I will tell you.

**Comment by eskimor** [comment]
Well if you allow any character - including newlines (nothing stops you from putting a newline in your string right) - how would you distinguish the next line of a header's value from the next header?

**Comment by lthms** [comment]
Afflax does not deal with this already?

**Comment by eskimor** [comment]
Good point. I don't think affjax does, but maybe the Xmlhttprequest stuff -  I have to check.

**Comment by lthms** [comment]
Yeah that was my second guess. I will try to check also.

**Comment by lthms** [comment]
Found this:
- https://bugzilla.mozilla.org/show_bug.cgi?id=297078 (2006, a security bug related to newline in header)
- http://stackoverflow.com/questions/941426/new-line-characters-get-submitted-differently (2009, a question about newlines)

From my understanding, it is effectively dealt with in xhr2, so we are good? (the second link is somehow irrelevant, sorry)

If you do not want to risk it, maybe we can add a function to removes newline?

**Comment by eskimor** [comment]
I think I will drop the url encoding for strings. I am not sure yet whether this is a good idea for more complex values (which are encoded generically). I'll think about it, fix to be expected soon.

**Comment by lthms** [comment]
I am not sure to understand. You want to never encode strings or it is just for headers? The first is not a good idea, the latter can be a good step. You should try to use a secret value with a special character such as `/` in you counter example, I think it will fail the same way it fails for a regular string.

**Comment by eskimor** [comment]
No - in the central-counter example there is no problem, because it uses a custom type `AuthToken` with generic json encoding - not the http-api-data default.

I want to never urlencode plain strings in headers - yes. I would still encode them when they are part of a bigger type - which is fine, because then the http-api-data default implementation does not trigger.

**Comment by lthms** [comment]
I will trust your judgement on this matter (: Thanks for your time!

**Comment by eskimor** [comment]
Well I also tried it - to be really sure, as I don't trust my judgement ;-)

Also interesting:

http://stackoverflow.com/questions/19028068/illegal-characters-in-http-headers#19028585

It still feels to be a good idea to just urlencode header values in the general case, except it conflicts with http-api-data defaults.

**Comment by eskimor** [comment]
Thank you for helping improving this library! :-)

**Comment by eskimor** [comment]
And you are right in the long run - something like ToHttpAPIData/FromHttpApiData for purescript will be a good idea - it is less convenient but offers greater control of the used format if you need it.

**Comment by lthms** [comment]
Should you close this PR, though? It appears, according to your last link, that my token is not a valid header indeed.

_Edit:_ well in fact, no, it’s for header names and not value.

> HTTP header values may contain any ISO-8859-1 character, though many of them needed to be transmitted within quotes. 

See [this link](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) for the relevant RFC section.

**Comment by eskimor** [comment]
Should be fixed in servant-purescript 0.5.0.0 together with purescript-servant-support 0.4.0. Please try!

**Comment by eskimor** [comment]
I am closing this now - please report if not yet fixed!

**Comment by lthms** [comment]
Thanks. Once again, it was a pleasure trying to fix this issue with you. I am looking forward to contribute again.

**Pull request closed without merging**
