### PR TITLE
Wrap QueryParams parameters in Maybe

### PR DESCRIPTION
**Pull request by mpodlasin**
I tested on my project and it works for single QueryParam values.

I did not test yet with QueryParams (Array of parameters) and with code with no query params at all.

### CODE REVIEW

**Comment by mpodlasin** [comment]
Also, shouldn't we leave code generated by tests in repo? That way we can see easily in pull request diffs how exactly the output will change.

**Comment by mpodlasin** [comment]
Ah, QueryParams (Array) shouldn't be wrapped in Maybe - it's equivalent to having an empty array - I will fix that.

**Comment by mpodlasin** [comment]
@eskimor Gentle ping. Will you review? This works for me very well.

**Comment by eskimor** [comment]
friendly reminder, greatly appreciated! I was under the impression that you wanted to fix something first. I will have a look tomorrow!

**Comment by eskimor** [comment]
Ok, it looks good! But could expand the "test suite" to handle query params so the implementation can be checked more easily? Thank you!

**Comment by mpodlasin** [comment]
Could you explain a bit what you want me to do? In `test/Spec` there are already `QueryParam` used?

**Comment by eskimor** [comment]
uuuuhm yeah. My fault, sorry about that. :-)

**Comment by eskimor** [comment]
Good work, thank you!

**Comment by mpodlasin** [comment]
Thanks for quick response! ;)

**Pull request merged**
