### PR TITLE
Purescript 0.11

### LINKED ISSUE #27: purescript 0.11 support
`servant-purescript` seems to be incompatible with purescript 0.11.

When building servant-purescript generated project, I get this error: 

    Error found:
    at src/ServerAPI.purs line 28, column 1 - line 28, column 1
    
      Unable to parse module:
      unexpected comma in constraints.
    
    Class constraints in type annotations can no longer be grouped in parentheses.
    Each constraint should now be separated by `=>`, for example:
        `(Applicative f, Semigroup a) => a -> f a -> f a`
      would now be written as:
        `Applicative f => Semigroup a => a -> f a -> f a`.
    
      expecting indentation past column 1, (, qualifier, proper name, operator or ->
    
    
    See https://github.com/purescript/documentation/blob/master/errors/ErrorParsingModule.md for more information,
    or to contribute content related to this error.
    
    
    * ERROR: Subcommand terminated with exit code 1

And line 28 contains 

    postMovieSearch :: forall eff m.
                       (MonadAsk (SPSettings_ SPParams_) m, MonadError AjaxError m, MonadAff ( ajax :: AJAX | eff) m)
                       => MovieSearch -> m (Array ResponseSimpleMovie)

### PR DESCRIPTION
**Pull request by legrostdg**
Fixes #27

### CODE REVIEW

**Comment by legrostdg** [comment]
Next error:

    Error found:
    in module ServerAPI
    at src/ServerAPI.purs line 10, column 1 - line 10, column 41
    
      Module Data.Argonaut.Printer was not found.
      Make sure the source file exists, and that it has been provided as an input to psc.

**Comment by themoritz** [comment]
@legrostdg it seems the `Data.Argonaut.Printer` module along with the `printJson` function was removed from purescript-argonaut-core. I think you can instead use `stringify` from `Data.Argonaut.Core` (see https://github.com/eskimor/servant-purescript/blob/0ee0700c6313cd3c2f93ce993ac33fac4c9d2656/src/Servant/PureScript/MakeRequests.hs#L111)

**Comment by legrostdg** [comment]
@themoritz Thanks, that was also my guess for an easy fix :-).

It compiles with my last commits.

**Comment by themoritz** [comment]
Awesome, thanks for making these changes!

**Comment by legrostdg** [comment]
also, partially fixes #18

**Pull request merged**
